/**
 * Starter regulation register tailored to a Portuguese textile / industrial
 * customer (Maxtil profile). Each entry is a real, published regulation
 * with its CELEX or DRE source where available. The seed is per-tenant
 * and only fires when the target company has zero regulations — so
 * customers stay in control of their own register and re-seeding is a
 * no-op once they've curated the list.
 *
 * Sources are public references (EUR-Lex, Diário da República, ISO,
 * GHG Protocol) — none of this is generated by an LLM (per Spec
 * Amendment A5).
 */

export type RegulationSeed = {
  title: string;
  type:
    | "EU_REGULATION"
    | "EU_DIRECTIVE"
    | "NATIONAL_LAW"
    | "NATIONAL_DECREE"
    | "GUIDANCE"
    | "REPORTING_STANDARD"
    | "REGULATORY_UPDATE"
    | "INTERNAL_COMPLIANCE_NOTE"
    | "OTHER";
  geography: string;
  topic:
    | "WASTE_MANAGEMENT"
    | "CARBON_FOOTPRINT"
    | "GHG_REPORTING"
    | "ESG_REPORTING"
    | "ENERGY"
    | "HAZARDOUS_WASTE"
    | "ENVIRONMENTAL_LICENSING"
    | "AUDIT_AND_DOCUMENTATION"
    | "INDUSTRIAL_COMPLIANCE"
    | "OTHER";
  summary: string;
  sourceReference: string | null;
  effectiveDate: Date | null;
  regulatoryStatus: "PROPOSED" | "IN_FORCE" | "SUPERSEDED" | "REPEALED";
  appliesToUs: boolean;
  priorityLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
};

export const regulationsSeed: RegulationSeed[] = [
  {
    title:
      "CSRD — Corporate Sustainability Reporting Directive (EU 2022/2464)",
    type: "EU_DIRECTIVE",
    geography: "EU",
    topic: "ESG_REPORTING",
    summary:
      "Mandates standardised sustainability reporting for large EU companies and listed SMEs, covering environmental, social, and governance impacts (double materiality). Implements the European Sustainability Reporting Standards (ESRS) and requires limited (later reasonable) third-party assurance.",
    sourceReference: "https://eur-lex.europa.eu/eli/dir/2022/2464",
    effectiveDate: new Date("2024-01-01"),
    regulatoryStatus: "IN_FORCE",
    appliesToUs: true,
    priorityLevel: "HIGH",
  },
  {
    title: "CBAM — Carbon Border Adjustment Mechanism (EU 2023/956)",
    type: "EU_REGULATION",
    geography: "EU",
    topic: "CARBON_FOOTPRINT",
    summary:
      "Levies a carbon price on imports of carbon-intensive goods (cement, iron and steel, aluminium, fertilisers, electricity, hydrogen) to prevent carbon leakage. Transitional phase requires quarterly reporting; financial obligations begin Jan 2026.",
    sourceReference: "https://eur-lex.europa.eu/eli/reg/2023/956",
    effectiveDate: new Date("2023-10-01"),
    regulatoryStatus: "IN_FORCE",
    appliesToUs: false,
    priorityLevel: "MEDIUM",
  },
  {
    title: "EU Waste Framework Directive (2008/98/EC, as amended)",
    type: "EU_DIRECTIVE",
    geography: "EU",
    topic: "WASTE_MANAGEMENT",
    summary:
      "Establishes the legal framework for waste in the EU: definitions, the waste hierarchy (prevention → reuse → recycling → recovery → disposal), extended producer responsibility, and recovery/disposal codes (R1–R13, D1–D15) used in our Waste Flows module.",
    sourceReference: "https://eur-lex.europa.eu/eli/dir/2008/98",
    effectiveDate: new Date("2008-12-12"),
    regulatoryStatus: "IN_FORCE",
    appliesToUs: true,
    priorityLevel: "HIGH",
  },
  {
    title: "EU Industrial Emissions Directive recast (2024/1785)",
    type: "EU_DIRECTIVE",
    geography: "EU",
    topic: "INDUSTRIAL_COMPLIANCE",
    summary:
      "Updates the IED (2010/75/EU) with stricter pollutant limits, new BAT conclusions, and extended scope to additional industrial activities. Operating permits must be reviewed against new BREFs within 4 years of publication.",
    sourceReference: "https://eur-lex.europa.eu/eli/dir/2024/1785",
    effectiveDate: new Date("2024-08-04"),
    regulatoryStatus: "IN_FORCE",
    appliesToUs: true,
    priorityLevel: "HIGH",
  },
  {
    title: "EU Strategy for Sustainable and Circular Textiles",
    type: "GUIDANCE",
    geography: "EU",
    topic: "INDUSTRIAL_COMPLIANCE",
    summary:
      "Commission strategy (COM/2022/141) setting the policy direction for the textile sector in the EU: Ecodesign requirements, EPR, ban on destruction of unsold textiles, due diligence on supply chains. Foundation for upcoming binding rules.",
    sourceReference:
      "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52022DC0141",
    effectiveDate: new Date("2022-03-30"),
    regulatoryStatus: "IN_FORCE",
    appliesToUs: true,
    priorityLevel: "MEDIUM",
  },
  {
    title:
      "Decreto-Lei n.º 102-D/2020 — Regime Geral da Gestão de Resíduos (RGGR)",
    type: "NATIONAL_DECREE",
    geography: "PT",
    topic: "WASTE_MANAGEMENT",
    summary:
      "Portuguese transposition of the EU Waste Framework Directive. Sets the national waste management regime: producer obligations, the LER (Lista Europeia de Resíduos), e-GAR (electronic waste tracking), and EPR schemes. Updated by DL 26-A/2024.",
    sourceReference:
      "https://dre.pt/dre/detalhe/decreto-lei/102-d-2020-150908012",
    effectiveDate: new Date("2021-01-01"),
    regulatoryStatus: "IN_FORCE",
    appliesToUs: true,
    priorityLevel: "CRITICAL",
  },
  {
    title:
      "Decreto-Lei n.º 127/2013 — Licenciamento ambiental (PCIP/IED transposition)",
    type: "NATIONAL_DECREE",
    geography: "PT",
    topic: "ENVIRONMENTAL_LICENSING",
    summary:
      "Establishes the integrated environmental licensing regime in Portugal (transposes the IED). Operators of installations listed in Anexo I require a Título Único Ambiental (TUA) reviewed against BAT conclusions.",
    sourceReference: "https://dre.pt/dre/detalhe/decreto-lei/127-2013-499412",
    effectiveDate: new Date("2013-10-15"),
    regulatoryStatus: "IN_FORCE",
    appliesToUs: true,
    priorityLevel: "HIGH",
  },
  {
    title:
      "Roteiro para a Neutralidade Carbónica 2050 (RNC 2050) — Resolução do Conselho de Ministros 107/2019",
    type: "NATIONAL_LAW",
    geography: "PT",
    topic: "CARBON_FOOTPRINT",
    summary:
      "Portugal's national net-zero strategy for 2050. Sets sectoral decarbonisation pathways including industry, with intermediate 2030 targets (-45 to -55% vs 2005). Underpins the Plano Nacional Energia e Clima 2030 (PNEC 2030).",
    sourceReference: "https://dre.pt/dre/detalhe/resolucao-conselho-ministros/107-2019-122777644",
    effectiveDate: new Date("2019-07-01"),
    regulatoryStatus: "IN_FORCE",
    appliesToUs: false,
    priorityLevel: "MEDIUM",
  },
  {
    title: "GHG Protocol Corporate Accounting and Reporting Standard",
    type: "REPORTING_STANDARD",
    geography: "GLOBAL",
    topic: "GHG_REPORTING",
    summary:
      "The most widely used international accounting tool for corporate greenhouse gas emissions. Defines Scopes 1, 2, 3 and the principles (relevance, completeness, consistency, transparency, accuracy) that govern our Carbon Footprint module. Aligned with ISO 14064-1.",
    sourceReference: "https://ghgprotocol.org/corporate-standard",
    effectiveDate: new Date("2004-01-01"),
    regulatoryStatus: "IN_FORCE",
    appliesToUs: true,
    priorityLevel: "HIGH",
  },
  {
    title: "ISO 14064-1:2018 — GHG quantification and reporting",
    type: "REPORTING_STANDARD",
    geography: "GLOBAL",
    topic: "GHG_REPORTING",
    summary:
      "International standard specifying principles and requirements at the organisation level for the quantification and reporting of greenhouse gas emissions and removals. Often paired with the GHG Protocol; required for accredited carbon-footprint verification.",
    sourceReference: "https://www.iso.org/standard/66453.html",
    effectiveDate: new Date("2018-12-01"),
    regulatoryStatus: "IN_FORCE",
    appliesToUs: true,
    priorityLevel: "MEDIUM",
  },
];
